name: Building
on: [push] 
  
  #push:
  #  tags:
  #  - "v*.*.*"

jobs: 
  building:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # copia el repositorio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        #run: poetry install
        run: poetry install 
      - name: Testing
        #run: poetry run pytest --junitxml=jest-junit.xml
        run: poetry run pytest --junitxml=jest-junit.xml --cov=modeltools --cov-report=lcov -cov-report=xml 
      - run: poetry build
      - name: Publish to GH release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/dist/*
      - name: test
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          #artifact: test-results            # artifact name
          name: JEST Tests                  # Name of the check run which will be created
          path: jest-junit.xml                     # Path to test results (inside artifact .zip)
          reporter: jest-junit              # Format of test results