name: Building
on: [push]
jobs: 
  building:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # copia el repositorio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install poetry
      - uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: poetry build
      - run: poetry build
      - run: ls ${{ github.workspace }}