name: Building
on: [push]
jobs: 
  building:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # copia el repositorio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install poetry
        uses: snok/install-poetry@v1
      - run: poetry build
      - name: Publish to GH release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/dist/*